-- 
-- Structure de la table userscores
--

DROP TABLE IF EXISTS userscores;
CREATE TABLE IF NOT EXISTS userscores (
  user_id mediumint(8) unsigned NOT NULL AUTO_INCREMENT,
  username varchar(255) NOT NULL default '',
  score int NOT NULL default 0,
  PRIMARY KEY (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 
-- Structure de la table openquizzdb
--

DROP TABLE IF EXISTS openquizzdb;
CREATE TABLE IF NOT EXISTS openquizzdb (
  quizz_id mediumint(8) unsigned NOT NULL AUTO_INCREMENT,
  langue varchar(2) NOT NULL default 'fr',
  theme varchar(100) NOT NULL default '',
  question varchar(255) NOT NULL default '',
  prop1 varchar(40) NOT NULL default '',
  prop2 varchar(40) NOT NULL default '',
  prop3 varchar(40) NOT NULL default '',
  prop4 varchar(40) NOT NULL default '',
  niveau char(1) NOT NULL default '',
  anecdote varchar(255) NOT NULL default '',
  wiki varchar(255) NOT NULL default '',
  PRIMARY KEY (quizz_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 
-- Contenu de la table openquizzdb
--

INSERT INTO
  openquizzdb (langue,theme,question,prop1,prop2,prop3,prop4,niveau,anecdote,wiki)
VALUES
  ('fr', 'Applications web', 'Quel logiciel de traitement de texte a été mis au point par la société Microsoft ?', '« Word »', '« Excel »', '« PowerPoint »', '« Access »', '1', 'Microsoft a déjà publié plusieurs logiciels de traitement de texte, mais « Word » en reste la « vedette ».', 'https://fr.wikipedia.org/wiki/Microsoft_Word'),
  ('fr', 'Applications web', 'Le logiciel « Excel », extrait de la suite bureautique Microsoft Office, est un...', 'Tableur', 'Traitement de texte', 'Navigateur internet', 'Messagerie', '1', 'Excel a été plusieurs fois critiqué pour ses problèmes de précision sur calculs à virgule flottante.', 'https://fr.wikipedia.org/wiki/Microsoft_Excel'),
  ('fr', 'Applications web', 'En informatique, comment appelle-t-on une erreur de programmation encore non localisée ?', 'Bug', 'Crack', 'Spam', 'Virus', '1', 'La gravité d\'un dysfonctionnement informatique peut aller de bénigne à majeure.', 'https://fr.wikipedia.org/wiki/Bug_(informatique)'),
  ('fr', 'Applications web', 'Quelle version de Windows Microsoft a-t-il lancée le vendredi 26 octobre 2012 ?', '« Windows 8 »', '« Windows 7 »', '« Windows CE »', '« Windows Mobile »', '1', 'La version de Windows 8.1 est une mise à jour gratuite de Windows 8, disponible depuis 2013.', 'https://fr.wikipedia.org/wiki/Windows_8'),
  ('fr', 'Applications web', 'Comment est communément abrégée la publication assistée par ordinateur ?', 'PAO', 'USB', 'VGA', 'CIO', '1', 'La PAO consiste à créer des documents imprimés en travaillant la composition et la typographie de documents.', 'https://fr.wikipedia.org/wiki/Publication_assistée_par_ordinateur'),
  ('fr', 'Applications web', 'Quelle application informatique de la société Apple permet de gérer facilement un iPod ?', '« iTunes »', '« QuickTime »', '« FileMaker »', '« HyperCard »', '1', '« iTunes » faisait partie de la suite logicielle d\'Apple « iLife » jusqu\'à la version \'06.', 'https://fr.wikipedia.org/wiki/ITunes'),
  ('fr', 'Applications web', 'En informatique, quel logiciel permet de créer des calculs automatiques ?', 'Tableur', 'Débogueur', 'Navigateur', 'Explorateur', '1', 'Une feuille de calcul est une table d\'informations, la plupart du temps financières.', 'https://fr.wikipedia.org/wiki/Tableur'),
  ('fr', 'Applications web', 'Quel pirate informatique casse les systèmes informatiques et les logiciels protégés ?', 'Hacker', 'Blagueur', 'Forceur', 'Pirateur', '1', 'Certains utilisent ce savoir-faire dans un cadre légal, d\'autres étant le plus souvent hors-la-loi.', 'https://fr.wikipedia.org/wiki/Hacker_(sécurité_informatique)'),
  ('fr', 'Applications web', 'Quels logiciels permettent de surfer sur Internet, sur PC, tablette ou smartphone ?', 'Navigateurs', 'Tableurs', 'Éditeurs', 'Émulateurs', '1', 'Le premier navigateur stable et largement diffusé fut « NCSA Mosaic », en 1993.', 'https://fr.wikipedia.org/wiki/Navigateur_Web'),
  ('fr', 'Applications web', 'Quel outil développé par le géant Google permet de gérer son emploi du temps ?', '« Google Agenda »', '« Google TimeLine »', '« Google Tempo »', '« Google Mobile »', '1', '« Google Agenda » permet de partager des événements et des agendas et de les publier sur internet ou sur un site Web.', 'https://fr.wikipedia.org/wiki/Google_Agenda'),
  ('fr', 'Applications web', 'Quelle grande société a reçu le feu vert en  2011 pour le rachat de « Skype » ?', 'Microsoft', 'Google', 'Apple', 'Facebook', '2', '« Skype » est un logiciel gratuit qui permet de passer des appels téléphoniques et vidéo via Internet, ainsi que le partage d\'écran.', 'https://fr.wikipedia.org/wiki/Skype'),
  ('fr', 'Applications web', 'Quel est probablement le plus connu des systèmes informatiques dits libres ?', 'Linux', 'Links', 'Lama', 'Lamento', '2', 'Linux est un système informatique qui fonctionne sur du matériel allant du téléphone portable au supercalculateur.', 'https://fr.wikipedia.org/wiki/Linux'),
  ('fr', 'Applications web', 'Quelle est le nom de la solution professionnelle de services Google ?', '« Google Apps »', '« Google Pro »', '« Google Serve »', '« Google Mac »', '2', 'Ce site Web au service des entreprises met en ligne de nombreuses applications.', 'https://fr.wikipedia.org/wiki/Google_Apps'),
  ('fr', 'Applications web', 'Quel type de logiciel est mis gratuitement et librement à disposition par son créateur ?', 'Freeware', 'Malware', 'Adware', 'Software', '2', 'Il ne faut toutefois pas confondre freeware (gratuiciel) et shareware (partagiciel).', 'https://fr.wikipedia.org/wiki/Freeware'),
  ('fr', 'Applications web', 'En avril 2012, quelle start-up Facebook a-t-il rachetée pour plus d\'un milliard de dollars ?', '« Instagram »', '« Globalnet »', '« Valve »', '« Backelite »', '2', '« Instagram » est une application  co-fondée et lancée par l\'américain Kevin Systrom et le Brésilien Michel Mike Krieger en octobre 2010.', 'https://fr.wikipedia.org/wiki/Instagram'),
  ('fr', 'Applications web', 'Au Québec, quel mot est souvent utilisé pour désigner le courrier électronique ?', 'Courriel', 'Emel', 'Lettrinter', 'Copitel', '2', 'Le courriel tend à être reconnu comme moyen valide de contacter une personne.', 'https://fr.wikipedia.org/wiki/Courrier_électronique'),
  ('fr', 'Applications web', 'Quel logiciel racheté par Microsoft a remplacé « Windows Live Messenger » en 2013 ?', '« Skype »', '« Instagram »', '« QuickTime »', '« Pidgin »', '2', '« Skype » a été fondé en Estonie par Niklas Zennström et Janus Friis en 2003 et développé par trois Estoniens à l\'origine du logiciel « KaZaA ».', 'https://fr.wikipedia.org/wiki/Skype'),
  ('fr', 'Applications web', 'Quel nom portait le précédent navigateur Internet devenu « Microsoft Edge » ?', '« Internet Explorer »', '« Safari »', '« Chrome »', '« Firefox »', '2', 'La version 11 du navigateur « Internet Explorer » sera toujours présente dans Windows 10 avant le passage progressif à « Microsoft Edge ».', 'https://fr.wikipedia.org/wiki/Internet_Explorer'),
  ('fr', 'Applications web', 'Quel logiciel est indispensable pour protéger votre ordinateur sur Internet ?', 'Antivirus', 'Chat', 'Navigateur', 'Messagerie', '2', 'Les antivirus peuvent balayer le contenu d\'un disque dur ainsi que la mémoire vive de l\'ordinateur.', 'https://fr.wikipedia.org/wiki/Logiciel_antivirus'),
  ('fr', 'Applications web', 'Qui est le tout premier pape à avoir envoyé un message sur « Twitter » ?', 'Benoît XVI', 'François', 'Jean-Paul II', 'Paul VI', '2', 'Réputé conservateur, le cardinal Ratzinger a été élu le 19 avril 2005 pour succéder à Jean-Paul II.', 'https://fr.wikipedia.org/wiki/Benoît_XVI'),
  ('fr', 'Applications web', 'Quel courrielleur créé par Mozilla est le compagnon idéal du navigateur « Firefox » ?', '« Thunderbird »', '« Incredimail »', '« Sylpheed »', '« Foxmail »', '3', 'Tout comme « Firefox », « Thunderbird » et son interface en XUL est basé sur le moteur Gecko.', 'https://fr.wikipedia.org/wiki/Mozilla_Thunderbird'),
  ('fr', 'Applications web', 'Quel nom porte la suite bureautique en ligne proposée par Microsoft ?', '« Office 365 »', '« KOffice »', '« OpenOffice »', '« StarOffice »', '3', 'Les abonnements « Office 365 » pour les particuliers permettent de bénéficier de la version complète de la suite Office que l\'on connaît.', 'https://fr.wikipedia.org/wiki/Microsoft_Office_365'),
  ('fr', 'Applications web', 'Quel était le nom de code de la version 3.1 de Microsoft Windows ?', 'Janus', 'Joke', 'Jumpman', 'Java', '3', 'La version 3 a été la première à connaître un large succès, permettant à Microsoft de rivaliser avec l\'Apple Macintosh.', 'https://fr.wikipedia.org/wiki/Windows_3.x'),
  ('fr', 'Applications web', 'Quel nom porte le service de stockage en ligne de Windows Live ?', '« Onedrive »', '« Dropbox »', '« RapidShare »', '« MediaFire »', '3', 'Ce service en ligne de stockage et d\'applications, créé en 2007, est une manifestation du concept de cloud computing.', 'https://fr.wikipedia.org/wiki/OneDrive'),
  ('fr', 'Applications web', 'Quel est le nouveau nom du logiciel gratuit de messagerie instantanée « Gaim » ?', '« Pidgin »', '« Connect »', '« iShare »', '« Komunity »', '3', '« Gaim » a été renommé en « Pidgin » en 2007 en raison de plaintes de la société AOL et de sa marque AIM.', 'https://fr.wikipedia.org/wiki/Pidgin_(logiciel)'),
  ('fr', 'Applications web', 'Quelle suite logicielle équivaut à Microsoft Office chez le géant Google ?', '« Google Documents »', '« OpenOffice »', '« Google Sites »', '« Works »', '3', '« Google Documents » est une suite des évolutions de « Google Spreadsheets » et de « Writely », logiciel de traitement de texte.', 'https://fr.wikipedia.org/wiki/Google_Documents'),
  ('fr', 'Applications web', 'De quel pays la suite logicielle gratuite « Opera » est-elle originaire ?', 'Norvège', 'France', 'Italie', 'Autriche', '3', '« Opera » est un navigateur Web développé par la société norvégienne Opera Software, qui propose plusieurs logiciels relatifs à Internet.', 'https://fr.wikipedia.org/wiki/Opera'),
  ('fr', 'Applications web', 'Lequel de ces outils ne permet pas de visionner des pages web ?', '« Acrobat Reader »', '« Mozilla Firefox »', '« Google Chrome »', '« Internet Explorer »', '3', 'Adobe change régulièrement le nom des produits de la famille Acrobat et cela en subdivisant sa gamme.', 'https://fr.wikipedia.org/wiki/Adobe_Acrobat_DC'),
  ('fr', 'Applications web', 'Combien de téléchargements dénombrait-on sur le célèbre « App Store » fin 2012 ?', '35 milliards', '25 milliards', '15 milliards', '5 milliards', '3', 'Depuis la mise à jour du système d\'exploitation d\'Apple iOS 7 en septembre 2013, l\'« App Store » possède un tout nouveau design.', 'https://fr.wikipedia.org/wiki/App_Store'),
  ('fr', 'Applications web', 'Quelle est la date officielle de création de « Wikipédia » en Français ?', '23 mars 2001', '2 janvier 1999', '15 janvier 2002', '8 décembre 2000', '3', 'Plusieurs moyens de consulter l\'encyclopédie existent, tels que des sites web miroirs ou des applications pour smartphone.', 'https://fr.wikipedia.org/wiki/Wikipédia_en_français'),
  ('fr', 'Culture G #1', 'Quel film à succès a réuni sur les écrans Sean Connery et Christophe Lambert ?', '« Highlander »', '« Subway »', '« Mad Max »', '« Greystoke »', '1', '« A Kind of Magic » est un album du groupe Queen, sorti en juin 1986, dont six de ses neuf morceaux sont utilisés dans le film « Highlander ».', 'https://fr.wikipedia.org/wiki/Highlander'),
  ('fr', 'Culture G #1', 'Quel pays, dont les premiers habitants étaient des Newars, a pour capitale Katmandou ?', 'Népal', 'Tibet', 'Corée du Nord', 'Pakistan', '1', 'Katmandou est la capitale politique et religieuse du Népal ainsi que la plus grande ville du pays.', 'https://fr.wikipedia.org/wiki/Katmandou'),
  ('fr', 'Culture G #1', 'Dans quel film John Travolta incarne-t-il un ange tombé du ciel ?', '« Michael »', '« Johnny »', '« Sam »', '« Jerry »', '1', 'Dans le film « Michael », deux journalistes enquêtent sur un soi-disant vrai ange vivant chez une dame âgée.', 'https://fr.wikipedia.org/wiki/Michael_(film,_1996)'),
  ('fr', 'Culture G #1', 'Pour quel auteur-compositeur-interprète aux 40 millions de disques Capri est-il fini ?', 'Hervé Vilard', 'Salvatore Adamo', 'Serge Lama', 'Charles Aznavour', '1', 'Didier Barbelivien, Michel Fugain et Danyel Gérard ont fait partie de la liste des artistes qui ont composé pour Hervé Vilard.', 'https://fr.wikipedia.org/wiki/Hervé_Vilard'),
  ('fr', 'Culture G #1', 'Quel peintre, né en 1844, est également appelé par beaucoup le Douanier ?', 'Henri Rousseau', 'Pablo Picasso', 'Edgar Degas', 'Salvador Dali', '1', 'Le premier portrait connu réalisé par le peintre Henri Rousseau semble être celui de sa première femme.', 'https://fr.wikipedia.org/wiki/Henri_Rousseau'),
  ('fr', 'Culture G #1', 'Quel personnage imaginaire fut popularisé par le roman de E.R. Burroughs et par le cinéma ?', 'Tarzan', 'King-Kong', 'Nessie', 'Le Yéti', '1', 'Edgar Rice Burroughs a inspiré bon nombre d\'auteurs de science-fiction et de fantastique ainsi que de nombreux réalisateurs.', 'https://fr.wikipedia.org/wiki/Edgar_Rice_Burroughs'),
  ('fr', 'Culture G #1', 'Quelle est la seule valeur à la roulette à porter la couleur verte ?', 'Zéro', 'Quarante', 'Cinquante', 'Treize', '1', 'À la roulette, lorsque le croupier donne la main, chaque joueur mise sur un numéro qu\'il espère être tiré pour remporter la mise.', 'https://fr.wikipedia.org/wiki/Roulette_(jeu_de_hasard)'),
  ('fr', 'Culture G #1', 'Quelle est la race du chien de Columbo, inspecteur perspicace de la télé ?', 'Basset', 'Beagle', 'Bichon', 'Bull-terrier', '1', 'Interrompue en 1978, la série télévisée « Columbo » a été ressuscitée en 1989, toujours avec Peter Falk dans le rôle principal.', 'https://fr.wikipedia.org/wiki/Columbo'),
  ('fr', 'Culture G #1', 'Quelle est la plus petite unité de mémoire utilisable sur un ordinateur ?', 'Bit', 'Byte', 'Bar', 'Becquerel', '1', 'La mémoire est un composant matériel essentiel de nombreux appareils électroniques, présent dans tous les ordinateurs.', 'https://fr.wikipedia.org/wiki/Mémoire_(informatique)'),
  ('fr', 'Culture G #1', 'Dans le langage familier, comment appelle-t-on la dent du petit enfant ?', 'Quenotte', 'Quartette', 'Quintuple', 'Quittance', '1', 'Il est important de bien se brosser les dents de manière régulière si l\'on veut éviter la prolifération de caries dans la bouche.', 'https://fr.wikipedia.org/wiki/Dent'),
  ('fr', 'Culture G #1', 'Où se situe la célèbre base navale américaine de Guantanamo, réputée pour sa sévérité ?', 'Cuba', 'Mexique', 'Hawaii', 'Paraguay', '2', 'La base de Guantanamo, très hautement sécurisée, détient des personnes et des individus qualifiés de combattants hors-la-loi.', 'https://fr.wikipedia.org/wiki/Prison_de_Guantánamo'),
  ('fr', 'Culture G #1', 'Quelle est la spécialité du sportif tunisien Oussama Mellouli ?', 'Natation', 'Marathon', 'Football', 'Boxe', '2', 'Oussama Mellouli est le premier champion olympique tunisien du milieu de la natation professionnelle à avoir remporté ce titre.', 'https://fr.wikipedia.org/wiki/Oussama_Mellouli'),
  ('fr', 'Culture G #1', 'Quel acteur français a remporté le premier rôle dans le film « Le Guépard » ?', 'Alain Delon', 'Claude Brasseur', 'Jean Gabin', 'Jean Reno', '2', 'Le film « Le Guépard », mettant en scène l\'acteur Alain Delon, décrit la chute de l\'aristocratie italienne, dont la scène du bal donne la clé.', 'https://fr.wikipedia.org/wiki/Le_Guépard_(film)'),
  ('fr', 'Culture G #1', 'Qui était le compagnon de Paul de Tarse, désigné aussi sous le nom de saint Paul ?', 'Saint Luc', 'Saint Matthieu', 'Saint Jean', 'Saint Marc', '2', 'Sans faire partie des Douze, Saint Paul a toutefois marqué le christianisme par son interprétation de l\'enseignement de Jésus.', 'https://fr.wikipedia.org/wiki/Paul_de_Tarse'),
  ('fr', 'Culture G #1', 'Quel titre de noblesse est immédiatement inférieur à celui de comte ?', 'Vicomte', 'Marquis', 'Duc', 'Archiduc', '2', 'Vicomte est une distinction héréditaire que beaucoup revendiquent mais à laquelle ne sont attachés aucuns pouvoirs.', 'https://fr.wikipedia.org/wiki/Vicomte'),
  ('fr', 'Culture G #1', 'Quelle est la capitale de la Nouvelle-Zélande, au sud-ouest de l\'océan Pacifique ?', 'Wellington', 'Washington', 'Worcester', 'Winnipeg', '2', 'Troisième ville la plus peuplée du pays, Wellington fait partie des douze meilleures villes dans laquelle vivre.', 'https://fr.wikipedia.org/wiki/Nouvelle-Zélande'),
  ('fr', 'Culture G #1', 'Quel film a réuni sur les écrans Isabelle Adjani et Sharon Stone ?', '« Diabolique »', '« Les sorcières »', '« Ange et Démon »', '« Les ensorceleuses »', '2', 'Dans le film « Diabolique », la femme et la maîtresse d\'un professeur s\'associent pour planifier son assassinat.', 'https://fr.wikipedia.org/wiki/Diabolique_(film)'),
  ('fr', 'Culture G #1', 'Comment est également appelée la Transat Jacques Vabre ?', 'Route du café', 'Route du rhum', 'Trophée du rhum', 'Vendée Globe', '2', 'La Transat Jacques Vabre ou route du café, course transatlantique en double, se déroule tous les deux ans depuis 1993.', 'https://fr.wikipedia.org/wiki/Transat_Jacques_Vabre'),
  ('fr', 'Culture G #1', 'Quel oiseau vivant dans l\'hémisphère nord nage le plus vite ?', 'Pingouin', 'Bécassine', 'Martinet', 'Pie', '2', 'Par abus de langage, le pingouin est souvent confondu avec le manchot, de par sa ressemblance avec le Grand Pingouin.', 'https://fr.wikipedia.org/wiki/Pingouin'),
  ('fr', 'Culture G #1', 'Quelle est la plus grosse des planètes de notre Système solaire ?', 'Jupiter', 'Saturne', 'Uranus', 'Neptune', '2', 'Jupiter est une planète géante gazeuse, la plus grosse planète du Système solaire.', 'https://fr.wikipedia.org/wiki/Jupiter_(planète)'),
  ('fr', 'Culture G #1', 'Apparu il y a 450 millions d\'années, à quelle classe animale le scorpion appartient-il ?', 'Arachnides', 'Reptiles', 'Insectes', 'Mammifères', '3', 'Les scorpions se distinguent des araignées par un aiguillon venimeux situé au bout de leur abdomen pouvant être mortel pour l\'homme.', 'https://fr.wikipedia.org/wiki/Scorpiones'),
  ('fr', 'Culture G #1', 'Quel frère d\'une actrice prénommée Mary a réalisé le film « La fièvre du samedi soir » ?', 'John Badham', 'John Travolta', 'John Payne', 'John Remezick', '3', '« La fièvre du samedi soir », réalisé par John Badham, fut un des principaux vecteurs de diffusion de la musique et de la mode disco.', 'https://fr.wikipedia.org/wiki/La_Fièvre_du_samedi_soir'),
  ('fr', 'Culture G #1', 'Au Moyen Âge, comment appelait-on un village fortifié ?', 'Bastide', 'Château fort', 'Rempart', 'Tour', '3', 'De nos jours, les bastides les plus connues sont celles de Monflanquin, Monpazier, Grenade ou bien encore Libourne.', 'https://fr.wikipedia.org/wiki/Bastide_(ville)'),
  ('fr', 'Culture G #1', 'Quelle ville du Kent est célèbre pour sa source miraculeuse ?', 'Tunbridge Wells', 'Gillingham', 'Dartford', 'Ramsgate', '3', 'Comme la reine Victoria, de nombreuses personnes célèbres sont venues en cure à Tunbridge Wells profiter de sa source miraculeuse.', 'https://fr.wikipedia.org/wiki/Tunbridge_Wells'),
  ('fr', 'Culture G #1', 'Quel apéritif à base de vin est aromatisé avec des plantes amères et toniques ?', 'Vermouth', 'Kokebok', 'Gentiane', 'Piccolo', '3', 'Dans une classification du plus sec au plus doux, on trouve le vermouth sec, le blanc, le rosé et le rouge.', 'https://fr.wikipedia.org/wiki/Vermouth'),
  ('fr', 'Culture G #1', 'À quel écrivain, membre de l\'Académie française, doit-on le roman intitulé « Le sagouin » ?', 'Mauriac', 'Giono', 'Camus', 'Barjavel', '3', 'Dans le roman « Le sagouin », écrit en quatre parties, on peut supposer que l\'action se passe vers 1920.', 'https://fr.wikipedia.org/wiki/Le_Sagouin'),
  ('fr', 'Culture G #1', 'Quel président Français trouva la mort dans une situation inhabituelle ?', 'Félix Faure', 'René Coty', 'Georges Pompidou', 'Raymond Poincaré', '3', 'Suite à ce décès inopiné, on a souvent dit de Félix Faure qu\'il était un président plus célèbre par sa mort que par sa vie.', 'https://fr.wikipedia.org/wiki/Félix_Faure'),
  ('fr', 'Culture G #1', 'Comment appelle-t-on le versant de la montagne non situé au soleil ?', 'Ubac', 'Upas', 'Urus', 'Uval', '3', 'Dans l\'hémisphère Nord, l\'ubac est généralement la face Nord d\'une montagne alors que l\'adret en représente la face Sud.', 'https://fr.wikipedia.org/wiki/Ubac'),
  ('fr', 'Culture G #1', 'Quel oiseau palmipède a pour particularité de construire un nid flottant ?', 'Grèbe', 'Grèle', 'Grève', 'Grène', '3', 'La position des pattes, très courtes et très en arrière par rapport au corps, a valu au grèbe le joli nom de pieds au derrière.', 'https://fr.wikipedia.org/wiki/Podicipedidae'),
  ('fr', 'Culture G #1', 'Un bédane, qui doit son nom à sa ressemblance avec un bec de canard, est un outil proche du...', 'Ciseau à bois', 'Maillet', 'Vilebrequin', 'Rabot', '3', 'Le bédane est un outil encore parfois utilisé aujourd\'hui pour réaliser des pièces en bois tournées entre pointes.', 'https://fr.wikipedia.org/wiki/Bédane'),
  ('fr', 'Grands monuments', 'Dans quel pays se dresse la Liberté éclairant le monde, ou Statue de la Liberté ?', 'États-Unis', 'France', 'Canada', 'Royaume-Uni', '1', 'Cette statue est située sur l\'île de Liberty Island au sud de Manhattan, à l\'embouchure de l\'Hudson et à proximité d\'Ellis Island.', 'https://fr.wikipedia.org/wiki/Statue_de_la_Liberté'),
  ('fr', 'Grands monuments', 'Dans quel État européen se situe la Sagrada Familia, consacrée par Benoît XVI en 2010 ?', 'Espagne', 'Portugal', 'Italie', 'Chypre', '1', 'C\'est l\'un des exemples les plus connus du modernisme catalan et un monument emblématique de la ville de Barcelone.', 'https://fr.wikipedia.org/wiki/Sagrada_Familia'),
  ('fr', 'Grands monuments', 'Dans quel pays peut-on voir les pyramides de Gizeh, classées depuis 1979 ?', 'Égypte', 'Afrique du Sud', 'Tunisie', 'Maroc', '1', 'Les trois plus grandes et plus célèbres des pyramides d\'Égypte sont celles de Khéops, Khéphren et Mykérinos.', 'https://fr.wikipedia.org/wiki/Pyramides_de_Gizeh'),
  ('fr', 'Grands monuments', 'Dans quel pays peut-on contempler la tour Eiffel, haute de 324 mètres ?', 'France', 'Italie', 'Royaume-Uni', 'États-Unis', '1', 'Construite par Gustave Eiffel, ce monument est devenu le symbole de la capitale française et un site touristique de premier plan.', 'https://fr.wikipedia.org/wiki/Tour_Eiffel'),
  ('fr', 'Grands monuments', 'Dans quel pays européen peut-on regarder le Colisée, à l\'origine amphithéâtre Flavien ?', 'Italie', 'Portugal', 'Espagne', 'Grèce', '1', 'Cet immense amphithéâtre ovoïde est le plus grand jamais construit dans l\'empire romain.', 'https://fr.wikipedia.org/wiki/Colisée'),
  ('fr', 'Grands monuments', 'Dans quelle ville peut-on entendre sonner Big Ben, énorme cloche de plus de 13 tonnes ?', 'Londres', 'Pékin', 'New York', 'Paris', '1', 'Big Ben se trouve au sommet de l\'Elizabeth Tower, la tour horloge du Palais de Westminster, qui est le siège du parlement britannique.', 'https://fr.wikipedia.org/wiki/Big_Ben'),
  ('fr', 'Grands monuments', 'Dans quel pays retrouve-t-on la plus grande muraille du monde jamais construite ?', 'Chine', 'Inde', 'France', 'Afrique du Sud', '1', 'Depuis 1987, la Grande Muraille de Chine est classée au patrimoine mondial de l\'UNESCO sous le numéro 438.', 'https://fr.wikipedia.org/wiki/Grande_Muraille'),
  ('fr', 'Grands monuments', 'Quel musée parisien, indissociable de sa pyramide, est connu dans le monde entier ?', 'Musée du Louvre', 'Musée Rodin', 'Musée Picasso', 'Musée de Cluny', '1', 'Le Louvre est le musée le plus visité au monde ainsi que le site culturel payant le plus visité de France.', 'https://fr.wikipedia.org/wiki/Musée_du_Louvre'),
  ('fr', 'Grands monuments', 'Dans quel pays se dresse le Machu Picchu, perché sur un promontoire rocheux ?', 'Pérou', 'Chili', 'Cambodge', 'Bolivie', '1', 'Machu Picchu, ville sacrée oubliée durant des siècles, est à ce jour considérée comme une oeuvre maîtresse de l\'architecture inca.', 'https://fr.wikipedia.org/wiki/Machu_Picchu'),
  ('fr', 'Grands monuments', 'Quel mur représente le lieu le plus sacré de la religion juive ?', 'Des Lamentations', 'Des sables', 'Des Noms', 'De la honte', '1', 'Le Mur des Lamentations est vénéré par les juifs pour sa proximité avec le Saint des Saints, situé sur le mont du Temple.', 'https://fr.wikipedia.org/wiki/Mur_des_Lamentations'),
  ('fr', 'Grands monuments', 'Qui a cassé le nez du Sphinx devant les grandes pyramides du plateau de Gizeh ?', 'Napoléon', 'Louis XV', 'Henri IV', 'Charles IX', '2', 'La suprématie des Blancs a conduit Napoléon à détruire le nez du Sphinx parce qu\'il rappelait trop la majesté de l\'homme noir.', 'https://fr.wikipedia.org/wiki/Sphinx_de_Gizeh'),
  ('fr', 'Grands monuments', 'Sur quelles îles se trouvent les Moaï, gigantesques ancêtres divinisés de pierre ?', 'Îles de Pâques', 'Îles Cook', 'Îles Galapagos', 'Îles de Noël', '2', 'La majorité des monolithes de l\'Île de Pâques est sculptée dans du tuf issu principalement de la carrière de Rano Raraku.', 'https://fr.wikipedia.org/wiki/Moaï'),
  ('fr', 'Grands monuments', 'Dans quel pays peut-on assister à un concert dans l\'opéra de Sydney ?', 'Australie', 'Antarctique', 'Samoa', 'Nouvelle-Zélande', '2', 'L\'opéra est aujourd\'hui une attraction touristique majeure de la ville bien que les visiteurs ne puissent assister aux représentations.', 'https://fr.wikipedia.org/wiki/Opéra_de_Sydney'),
  ('fr', 'Grands monuments', 'Aux États-Unis, quel célèbre bâtiment possède une forme de plan particulière ?', 'Pentagone', 'Kirkbride', 'Graceland', 'Pickfair', '2', 'Cet immeuble de cinq étages, inauguré le 15 janvier 1943, est le plus vaste immeuble de bureaux du monde.', 'https://fr.wikipedia.org/wiki/Pentagone_(États-Unis)'),
  ('fr', 'Grands monuments', 'Quel grand monument métallique est représentatif de la ville de Bruxelles ?', 'Atomium', 'Voortrekker', 'Luizenmolen', 'Tour et Taxis', '2', 'L\'Atomium représente la maille conventionnelle du cristal de fer (structure cubique centrée) agrandie 165 milliards de fois.', 'https://fr.wikipedia.org/wiki/Atomium'),
  ('fr', 'Grands monuments', 'Dans laquelle de ces villes retrouve-t-on une réplique à échelle réduite de la tour Eiffel ?', 'Las Vegas', 'Chicago', 'Hong Kong', 'Moscou', '2', 'La réplique de 165 mètres se situe en face de l\'hôtel-casino Paris Las Vegas sur le Las Vegas Strip.', 'https://fr.wikipedia.org/wiki/Répliques_et_imitations_de_la_tour_Eiffel'),
  ('fr', 'Grands monuments', 'Quel pont-aqueduc romain comportant trois étages enjambe le Gardon ?', 'Pont du Gard', 'Pont Caquot', 'Pont Napoléon', 'Pont de Seyssel', '2', 'Le pont du Gard assurait dans sa fonction première la continuité de l\'aqueduc romain qui conduisait l\'eau d\'Uzès à Nîmes.', 'https://fr.wikipedia.org/wiki/Pont_du_Gard'),
  ('fr', 'Grands monuments', 'Dans quel pays se trouve Angkor Vat, sur le site archéologique d\'Angkor ?', 'Cambodge', 'Vietnam', 'Thaïlande', 'Laos', '2', 'Les ruines d\'Angkor sont situées dans les forêts au nord du Tonlé Sap, en bordure de la ville de Siem Reap.', 'https://fr.wikipedia.org/wiki/Angkor'),
  ('fr', 'Grands monuments', 'Dans quelle ville française peut-on retrouver une tour surnommée « Le Crayon » ?', 'Lyon', 'Limoges', 'Bordeaux', 'Toulouse', '2', 'La Tour Part-Dieu est un gratte-ciel de bureaux situé dans le quartier de la Part-Dieu à Lyon, en France.', 'https://fr.wikipedia.org/wiki/Tour_Part-Dieu'),
  ('fr', 'Grands monuments', 'Quels temples creusés dans la falaise ont été construits par le pharaon Ramsès II ?', 'Abou Simbel', 'Péluse', 'Mallawi', 'Esna', '2', 'Les temples ont été construits sur le Nil au nord du lac Nasser, à environ 70 kilomètres de la deuxième cataracte du Nil.', 'https://fr.wikipedia.org/wiki/Temples_d\'Abou_Simbel'),
  ('fr', 'Grands monuments', 'Quel pays renferme la Tour de Belém, inscrite au patrimoine mondial de l\'UNESCO ?', 'Portugal', 'Israël', 'Espagne', 'Égypte', '3', 'La Tour de Belém a été construite sur les bords du Tage dans la freguesia de Santa Maria de Belém entre 1515 et 1521.', 'https://fr.wikipedia.org/wiki/Tour_de_Belém'),
  ('fr', 'Grands monuments', 'Dans quel pays africain se situe le Voortrekker Monument consacré aux pionniers boers ?', 'Afrique du Sud', 'Mali', 'Égypte', 'Ghana', '3', 'Symbole du nationalisme afrikaner, le monument se dresse depuis 1949 sur une colline à l\'entrée sud de la capitale sud-africaine.', 'https://fr.wikipedia.org/wiki/Voortrekker_Monument'),
  ('fr', 'Grands monuments', 'Dans quel État sud-américain peut-on admirer une célèbre statue de Carlos Pellegrini ?', 'Argentine', 'Bolivie', 'Colombie', 'Brésil', '3', 'Durant sa période présidentielle, Carlos Pellegrini réussit à assainir les finances de l\'État et créa la Banque de la Nation Argentine.', 'https://fr.wikipedia.org/wiki/Carlos_Pellegrini'),
  ('fr', 'Grands monuments', 'Combien d\'étages possède la tour de Pise, sur la Piazza dei Miracoli ?', 'Huit', 'Cinq', 'Dix', 'Treize', '3', 'La célébrité de la tour de Pise vient notamment de son inclinaison caractéristique, qui est actuellement d\'un angle de 3°59\' vers le sud.', 'https://fr.wikipedia.org/wiki/Tour_de_Pise'),
  ('fr', 'Grands monuments', 'Depuis 1934, qu\'est devenue la basilique Sainte-Sophie de Constantinople ?', 'Musée', 'Hôtel', 'Eglise', 'Mosquée', '3', 'La basilique est dédiée au Christ, « Sagesse de Dieu », selon la tradition théologique chrétienne.', 'https://fr.wikipedia.org/wiki/Sainte-Sophie_(Constantinople)'),
  ('fr', 'Grands monuments', 'Combien de noms de savants sont gravés sur la base du premier étage de la Tour Eiffel ?', '72', '55', '87', '64', '3', 'Gustave Eiffel a fait graver 72 noms de scientifiques, ingénieurs ou industriels qui ont honoré la France de 1789 à 1889.', 'https://fr.wikipedia.org/wiki/Liste_des_soixante-douze_noms_de_savants_inscrits_sur_la_tour_Eiffel'),
  ('fr', 'Grands monuments', 'Quel est le style du Parthénon de l\'Acropole à Athènes, réalisé en marbre du Pentélique ?', 'Dorique', 'Corinthien', 'Éolique', 'Ionique', '3', 'Le Parthénon était consacré à la déesse Athéna Parthénos, protectrice de la cité et déesse de la guerre et de la sagesse.', 'https://fr.wikipedia.org/wiki/Parthénon'),
  ('fr', 'Grands monuments', 'Quelle est la longueur du célèbre pont de pierre de Bordeaux ?', '487 mètres', '560 mètres', '339 mètres', '621 mètres', '3', 'Le pont de pierre de Bordeaux est construit en pierre et en brique, avec la particularité de comporter des espaces vides intérieurs.', 'https://fr.wikipedia.org/wiki/Pont_de_pierre_(Bordeaux)'),
  ('fr', 'Grands monuments', 'Quelle gare française classée a été mise en avant dans une publicité de la marque Chanel ?', 'Gare de Limoges', 'Gare de Toulouse', 'Gare de Lyon', 'Gare de Bordeaux', '3', 'L\'esthétique de la gare de Limoges actuelle emprunte autant à un Art nouveau tardif qu\'à l\'Art déco et au néoclassicisme.', 'https://fr.wikipedia.org/wiki/Gare_de_Limoges-Bénédictins'),
  ('fr', 'Grands monuments', 'Où pouvez-vous visiter le palais Jacques-Coeur, chef-d\'oeuvre de l\'architecture gothique ?', 'Bourges', 'Bordeaux', 'Blois', 'Besançon', '3', 'Cet édifice est né de la volonté du riche marchand Jacques Coeur de bâtir une grand\' maison dans sa ville natale.', 'https://fr.wikipedia.org/wiki/Palais_Jacques-Coeur');
  
  